### ISSUE TITLE
`make` fails

### ISSUE THREAD

**Issue by strogonoff** [metanorma/mn-samples-ogc#10]
When I run make, I get the following:

```
$ make
...
Bundle complete! 2 Gemfile dependencies, 67 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
BUILT_TARGET=repos/ogc-tcpnp/ogc-tcpnp.xml; \
	if [ "$BUILT_TARGET" != "null" ]; then \
	cp "$BUILT_TARGET" sources/ogc-tcpnp.xml; \
	fi
cp: repos/ogc-tcpnp/ogc-tcpnp.xml: No such file or directory
make: *** [sources/ogc-tcpnp.xml] Error 1
```

**Comment by opoudjis** [comment]
Same. I did not create this repo, and I'd rather someone else fix it.

**Comment by ronaldtse** [comment]
@strogonoff you have to run `make init-modules update-modules` first.

**Comment by strogonoff** [comment]
@ronaldtse right. Those targets are actually absent in Makefile (which threw me off), but I used `--recursive` and got over that error. However, I am getting this now:

```
BUILT_TARGET=repos/ogc-tcpnp/ogc-tcpnp.xml; \
	if [ "$BUILT_TARGET" != "null" ]; then \
	cp "$BUILT_TARGET" sources/ogc-tcpnp.xml; \
	fi
BUILT_TYPE=ogc; \
	RAW_COMMAND="bundle exec metanorma FILENAME"; \
	if [ "$BUILT_TYPE" != "null" ]; then \
	COMMAND="${RAW_COMMAND/FILENAME/-t $BUILT_TYPE sources/ogc-tcpnp.xml}"; \
	else \
	COMMAND="${RAW_COMMAND/FILENAME/sources/ogc-tcpnp.xml}"; \
	fi; \
	$COMMAND;
bundler: failed to load command: metanorma (/Users/tonys/.rvm/gems/ruby-2.5.5/bin/metanorma)
RuntimeError: internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'puppeteer'
Require stack:
- /Users/tonys/.rvm/gems/ruby-2.5.5/gems/metanorma-0.3.14/bin/metanorma-pdf.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/tonys/.rvm/gems/ruby-2.5.5/gems/metanorma-0.3.14/bin/metanorma-pdf.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/tonys/.rvm/gems/ruby-2.5.5/gems/metanorma-0.3.14/bin/metanorma-pdf.js'
  ]
}

  /Users/tonys/.rvm/gems/ruby-2.5.5/gems/metanorma-0.3.14/lib/metanorma/output/pdf.rb:18:in `convert'
  /Users/tonys/.rvm/gems/ruby-2.5.5/gems/isodoc-1.0.0/lib/isodoc/pdf_convert.rb:33:in `convert'
  /Users/tonys/.rvm/gems/ruby-2.5.5/gems/metanorma-ogc-0.2.0/lib/metanorma/ogc/processor.rb:36:in `output'
  /Users/tonys/.rvm/gems/ruby-2.5.5/gems/metanorma-0.3.14/lib/metanorma/compile.rb:192:in `block in process_extensions'
  /Users/tonys/.rvm/gems/ruby-2.5.5/gems/metanorma-0.3.14/lib/metanorma/compile.rb:183:in `each'
  /Users/tonys/.rvm/gems/ruby-2.5.5/gems/metanorma-0.3.14/lib/metanorma/compile.rb:183:in `process_extensions'
  /Users/tonys/.rvm/gems/ruby-2.5.5/gems/metanorma-0.3.14/lib/metanorma/compile.rb:20:in `compile'
  /Users/tonys/.rvm/gems/ruby-2.5.5/gems/metanorma-cli-1.2.4/lib/metanorma/cli/compiler.rb:27:in `compile_file'
  /Users/tonys/.rvm/gems/ruby-2.5.5/gems/metanorma-cli-1.2.4/lib/metanorma/cli/compiler.rb:13:in `compile'
  /Users/tonys/.rvm/gems/ruby-2.5.5/gems/metanorma-cli-1.2.4/lib/metanorma/cli/compiler.rb:17:in `compile'
  /Users/tonys/.rvm/gems/ruby-2.5.5/gems/metanorma-cli-1.2.4/lib/metanorma/cli/command.rb:34:in `compile'
  /Users/tonys/.rvm/gems/ruby-2.5.5/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/tonys/.rvm/gems/ruby-2.5.5/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/tonys/.rvm/gems/ruby-2.5.5/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/tonys/.rvm/gems/ruby-2.5.5/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/tonys/.rvm/gems/ruby-2.5.5/gems/metanorma-cli-1.2.4/lib/metanorma/cli.rb:59:in `start'
  /Users/tonys/.rvm/gems/ruby-2.5.5/gems/metanorma-cli-1.2.4/exe/metanorma:20:in `<top (required)>'
  /Users/tonys/.rvm/gems/ruby-2.5.5/bin/metanorma:23:in `load'
  /Users/tonys/.rvm/gems/ruby-2.5.5/bin/metanorma:23:in `<top (required)>'
make: *** [sources/ogc-tcpnp.html] Error 1
rm sources/ogc-tcpnp.html sources/ogc-tcpnp.xml
```

**Comment by strogonoff** [comment]
I have `puppeteer` installed globally, but apparently that doesn’t work, trying to troubleshoot

**Comment by strogonoff** [comment]
I have fixed an issue with my `puppeteer` installation and it works. Updated README with notes about submodules and `puppeteer`.
